export const OSMO_MEDIUM_TX_FEE = '0.0125';
export const fiatCurrency = {
    currency: "usd",
    symbol: "$",
    maxDecimals: 2,
    locale: "en-US",
};
export const mintCurrency = {
    coinDenom: "OSMO",
    coinMinimalDenom: "uosmo",
    coinDecimals: 6,
    coinGeckoId: "osmosis",
    coinImageUrl: "img/tokens/osmosis.svg",
};

export const poolInfoList = [
    {
      coinDenom: "OSMO",
      coinMinimalDenom: "uosmo",
      coinDecimals: 6,
      coinGeckoId: "osmosis",
      coinImageUrl: "img/tokens/osmosis.svg",
    },
    {
      coinDenom: "ION",
      coinMinimalDenom: "uion",
      coinDecimals: 6,
      coinGeckoId: "ion",
      coinImageUrl: "img/tokens/ion.png",
    },
    {
      coinDenom: "ATOM",
      coinMinimalDenom: "uatom",
      coinDecimals: 6,
      coinGeckoId: "cosmos",
      coinImageUrl: "img/tokens/cosmos.svg",
    },
    {
      coinDenom: "LUNA",
      coinMinimalDenom: "uluna",
      coinDecimals: 6,
      coinGeckoId: "terra-luna",
      coinImageUrl: "img/tokens/luna.png",
    },
    {
      coinDenom: "UST",
      coinMinimalDenom: "uusd",
      coinDecimals: 6,
      coinGeckoId: "terrausd",
      coinImageUrl: "img/tokens/ust.png",
    },
    {
      coinDenom: "KRT",
      coinMinimalDenom: "ukrw",
      coinDecimals: 6,
      coinGeckoId: "terra-krw",
      coinImageUrl: "img/tokens/krt.png",
    },
    {
      coinDenom: "SCRT",
      coinMinimalDenom: "uscrt",
      coinDecimals: 6,
      coinGeckoId: "secret",
      coinImageUrl: "img/tokens/scrt.svg",
    },
    {
      coinDenom: "AKT",
      coinMinimalDenom: "uakt",
      coinDecimals: 6,
      coinGeckoId: "akash-network",
      coinImageUrl: "img/tokens/akt.svg",
    },
    {
      coinDenom: "REGEN",
      coinMinimalDenom: "uregen",
      coinDecimals: 6,
      coinImageUrl: "img/tokens/regen.png",
      coinGeckoId: "regen",
    },
    {
      coinDenom: "DVPN",
      coinMinimalDenom: "udvpn",
      coinDecimals: 6,
      coinGeckoId: "sentinel",
      coinImageUrl: "img/tokens/dvpn.png",
    },
    {
      coinDenom: "XPRT",
      coinMinimalDenom: "uxprt",
      coinDecimals: 6,
      coinGeckoId: "persistence",
      coinImageUrl: "img/tokens/xprt.png",
    },
    {
      coinDenom: "IRIS",
      coinMinimalDenom: "uiris",
      coinDecimals: 6,
      coinGeckoId: "iris-network",
      coinImageUrl: "img/tokens/iris.svg",
    },
    {
      coinDenom: "CRO",
      coinMinimalDenom: "basecro",
      coinDecimals: 8,
      coinGeckoId: "crypto-com-chain",
      coinImageUrl: "img/tokens/cro.png",
    },
    {
      coinDenom: "IOV",
      coinMinimalDenom: "uiov",
      coinDecimals: 6,
      coinGeckoId: "starname",
      coinImageUrl: "img/tokens/iov.png",
    },
    {
      coinDenom: "NGM",
      coinMinimalDenom: "ungm",
      coinDecimals: 6,
      coinGeckoId: "e-money",
      coinImageUrl: "img/tokens/ngm.png",
    },
    {
      coinDenom: "EEUR",
      coinMinimalDenom: "eeur",
      coinDecimals: 6,
      coinGeckoId: "e-money-eur",
      coinImageUrl: "img/tokens/eeur.png",
    },
    {
      coinDenom: "JUNO",
      coinMinimalDenom: "ujuno",
      coinDecimals: 6,
      coinGeckoId: "juno-network",
      coinImageUrl: "img/tokens/juno.svg",
    },
    {
      coinDenom: "TICK",
      coinMinimalDenom: "utick",
      coinDecimals: 6,
      coinGeckoId: "pool:utick",
      coinImageUrl: "img/tokens/tick.svg",
    },
    {
      coinDenom: "LIKE",
      coinMinimalDenom: "nanolike",
      coinDecimals: 9,
      coinGeckoId: "likecoin",
      coinImageUrl: "img/tokens/likecoin.svg",
    },
    {
      coinDenom: "IXO",
      coinMinimalDenom: "uixo",
      coinDecimals: 6,
      coinGeckoId: "pool:uixo",
      coinImageUrl: "img/tokens/ixo.svg",
    },
    {
      coinDenom: "BCNA",
      coinMinimalDenom: "ubcna",
      coinDecimals: 6,
      coinGeckoId: "bitcanna",
      coinImageUrl: "img/tokens/bcna.svg",
    },
    {
      coinDenom: "BTSG",
      coinMinimalDenom: "ubtsg",
      coinDecimals: 6,
      coinGeckoId: "pool:ubtsg",
      coinImageUrl: "img/tokens/btsg.svg",
    },
    {
      coinDenom: "XKI",
      coinMinimalDenom: "uxki",
      coinDecimals: 6,
      coinGeckoId: "pool:uxki",
      coinImageUrl: "img/tokens/ki.svg",
    },
    {
      coinDenom: "MED",
      coinMinimalDenom: "umed",
      coinDecimals: 6,
      coinGeckoId: "medibloc",
      coinImageUrl: "img/tokens/med.png",
    },
    {
      coinDenom: "BOOT",
      coinMinimalDenom: "boot",
      coinDecimals: 0,
      coinGeckoId: "pool:boot",
      coinImageUrl: "img/tokens/boot.png",
    },
    {
      coinDenom: "CMDX",
      coinMinimalDenom: "ucmdx",
      coinDecimals: 6,
      coinGeckoId: "pool:ucmdx",
      coinImageUrl: "img/tokens/cmdx.png",
    },
    {
      coinDenom: "CHEQ",
      coinMinimalDenom: "ncheq",
      coinDecimals: 9,
      coinGeckoId: "cheqd-network",
      coinImageUrl: "img/tokens/cheq.svg",
    },
    {
      coinDenom: "STARS",
      coinMinimalDenom: "ustars",
      coinDecimals: 6,
      coinGeckoId: "pool:ustars",
      coinImageUrl: "img/tokens/stars.png",
    },
    {
      coinDenom: "HUAHUA",
      coinMinimalDenom: "uhuahua",
      coinDecimals: 6,
      coinGeckoId: "pool:uhuahua",
      coinImageUrl: "img/tokens/huahua.png",
    },
    {
      coinDenom: "LUM",
      coinMinimalDenom: "ulum",
      coinDecimals: 6,
      coinGeckoId: "pool:ulum",
      coinImageUrl: "img/tokens/lum.svg",
    },
  ];
  